### ISSUE TITLE
Document cause of `invalid arithmetic operator (error token is "'t + 0")`

### ISSUE THREAD

**Issue by jpluimers** [agronick/btrfs-size#3]
On OpenSuSE Tumbleweed, I got this:

```
./btrfs-size.sh: line 55: can't + 0: syntax error: invalid arithmetic operator (error token is "'t + 0")
```

It was caused by not having quota enabled.

The no-so-nice thing about btrfs is that you can do `btrfs quota enable /` but there is no btrfs command to tell quota is in fact enabled.

Please document that if you get the above error, then you need to enable btrfs quotas.

**Comment by nachoparker** [comment]
Hi, seeing that no PRs are being accepted, I wrote my own version, which is much faster and doesn't require quotas to be enabled

https://ownyourbits.com/2017/12/06/check-disk-space-of-your-btrfs-snapshots-with-btrfs-du/

Hope it helps
