### ISSUE TITLE
How to check subvolume size of subvolumes not belonging to /

### ISSUE THREAD

**Issue by cmonty14** [agronick/btrfs-size#9]
Hi,
I have created BTRFS on an external device in order to store backups.
For creating backups I use snapper + [snap-sync](github.com/wesbarnett/snap-sync).

My question is:
How can I check the size of the subvolumes located on the external device that is mounted to _/backup_?

When I execute the script the output shows only snapshots belonging to /.

THX

**Comment by agronick** [comment]
The location is the only parameter it takes. Just put it after the command.
